export type UserProfileDataType = {
  id: string;
  userId: string;
  avatarUrl?: string;
  location?: string;
  about?: string;
  occupation?: string;
  followerCount?: number;
  followingCount?: number;
  forkedCount?: number;
  likedCount?: number;
  dislikedCount?: number;
  createdAt?: Date;
  updatedAt?: Date;
  twitterUsername?: string;
  facebookUsername?: string;
  linkedInUsername?: string;
  instagramUsername?: string;
  website?: string;
};
